#!/usr/bin/python3

import sys
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()
path = modems[0][0]

if (len(sys.argv) == 3):
	path = sys.argv[1]
	volume = sys.argv[2]
else:
	volume = sys.argv[1]

cv = dbus.Interface(bus.get_object('org.ofono', path),
						'org.ofono.CallVolume')

cv.SetProperty("MicrophoneVolume", dbus.Byte(int(volume)))
